language: node_js
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
node_js:
  - "8"
before_script:
  - yarn lerna bootstrap
script:
  - yarn lint:ci
  - yarn flow:ci
  - yarn test:ci
